// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAxGPzki72RGRZcHwj6bQBBDO8nrAWZfOA',
    appId: '1:477848243780:web:fe6ac3976c55c895b3b611',
    messagingSenderId: '477848243780',
    projectId: 'simplelogin-5a914',
    authDomain: 'simplelogin-5a914.firebaseapp.com',
    storageBucket: 'simplelogin-5a914.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDhcSozQYECGx5r-ins-c8ZF1vOPMAjbFg',
    appId: '1:477848243780:android:b391dfcdb88640aeb3b611',
    messagingSenderId: '477848243780',
    projectId: 'simplelogin-5a914',
    storageBucket: 'simplelogin-5a914.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCsZA5LZqD4k3OYiP7ojtFt6Bwes4Y_02o',
    appId: '1:477848243780:ios:9a15d648e8d4a4e8b3b611',
    messagingSenderId: '477848243780',
    projectId: 'simplelogin-5a914',
    storageBucket: 'simplelogin-5a914.appspot.com',
    iosBundleId: 'com.example.simpleLogin',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCsZA5LZqD4k3OYiP7ojtFt6Bwes4Y_02o',
    appId: '1:477848243780:ios:6d202a036e87482db3b611',
    messagingSenderId: '477848243780',
    projectId: 'simplelogin-5a914',
    storageBucket: 'simplelogin-5a914.appspot.com',
    iosBundleId: 'com.example.simpleLogin.RunnerTests',
  );
}
